apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
#   namespace: 
spec:
  replicas: 2    
  selector:
    matchLabels:
      app: go
  template:
    metadata:
       name: go-deployment
       labels:
         app: go
    spec:
      containers:
        - name: latest
          image: vijyant97/dev:0.1.70
          ports:
          - containerPort: 8080
          resources:
            requests:
             cpu: "10m"

