version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.03
        auth:
          username: vijyant97
          password: Vijyant@7   # Replace with your DockerHub password
    working_directory: /workspace/circleci
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          # docker build - < dockerfile
          docker build -t vijyant97/dev:golang .
          # echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push vijyant97/dev:golang 
      # - run: |    
      #     name:
workflow:
  build_push_docker:
    jobs:
      - build
      - setup_remote_docker
      - run
