version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.03
        auth:
          username: vijyant97
          password: Vijyant@7   # Replace with your DockerHub password
    working_directory: ~/workspace/circleci
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          # docker build - < dockerfile
          docker build -t vijyant97/dev:${TAG} .
          echo $DOCKER_PASS | docker login -u vijyant97 --password-stdin
          docker push vijyant97/dev:${TAG}

  deploytoeks:
    docker:
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_REGION
    working_directory:  ~/workspace/circleci
    steps:
      - checkout
      - run:
          name: "Deploying to EKS"
          command: |
            apt-get update -y
            apt-get install awscli -y
            apt-get install kubectl -y
            aws eks --region eu-west-1 update-kubeconfig --name go-test-cluster
            sed -i 's/\(image:.*\)/\1\n      tag: '$TAG'/' deploy/k8s/deployment.yaml
            kubectl apply -f deploy/k8s/deployment.yaml
        
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploytoeks
          