name: sonarqube 
on:
  # Trigger analysis when push or pull requests
  push:
    branches: [main]
  pull_request:
    branches: [main]      

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: [self-hosted , clops-vijyant]
    steps:
    - 
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - 
      name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
