name: sonarqube 
on:
  # Trigger analysis when push or pull requests
  push:
    branches: [sonarcloud]
  pull_request:
    branches: [sonarcloud]      

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: [self-hosted , clops-vijyant]
    steps:
    - 
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - 
      name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
