name: nexus
on:
  # Trigger analysis when push or pull requests
  push:
   # branches: [main]
    branches: ['*']
   # branches: '!main'
  pull_request:
   # branches: [main]
    branches: ['*']

jobs:
  build_and_upload:
    name: build
    runs-on: [self-hosted , clops-vijyant]
    # env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - 
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml   
    - 
      name: Nexus Repository Publisher for GitHub Actions
      uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
      with:
        serverUrl: http://99.80.60.200:8081/
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        format: maven2
        repository: sample-java-app-snapshot
        coordinates: groupId=clops.nexus.actions artifactId=hello-world version=1.0
        assets: extension=jar
        filename: ./target/hello-world-1.0.jar

        
    # - name: Slack Notification
    #   uses: act10ns/slack@v1
    #   with: 
    #     status: ${{ job.status }}
    #     steps: ${{ toJson(steps) }}
    #     channel: '#test123'
    #   if: always()
