name: nexus
on:
  # Trigger analysis when push or pull requests
  push:
    branches: [actions-nexus-java]
   # branches: ['*']
   # branches: '!main'
  pull_request:
    branches: [actions-nexus-java]
#     branches: ['*']

jobs:
  build_and_upload:
    name: build
    runs-on: [self-hosted , clops-vijyant]
    # env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Github actions Maven Build
      run: mvn -B package --file=pom.xml
      
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        
#     -  run: |                
#         # mkdir ~/.m2 
#         cp -r settings.xml ~/.m2/
#         mvn deploy -X
#        :deploy-file
#         --settings=~/.m2/settings.xml
#         -Dfile=./target/hello-world-1.0-SNAPSHOT.jar \
#         -Durl=http://99.80.60.200:8081/ \
#         -DgeneratePom=false \
#         -DgroupId=clops.nexus.actions \
#         -DartifactId=hello-world \
#         -Dversion=1.0 \
#         -Dpackaging=jar \ 
#         -DrepositoryId=sample-java-app-snapshot
               
#     - name: Nexus Repository Publisher for GitHub Actions
#       uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
#       with:
#         serverUrl: http://99.80.60.200:8081/repository/sample-java-app-snapshot/
#         username: admin
#         #${{ secrets.NEXUS_USER }}
#         password: Vijyant@7
#         #${{ secrets.NEXUS_PASS }}
#         format: maven2
#         repository: sample-java-app-snapshot
#         coordinates: groupId=clops.gitact.vijyant artifactId=hello-world version=1.0-SNAPSHOT
#         assets: extension=jar
#         filename: ./target/hello-world-1.0-SNAPSHOT.jar
        
    # - name: Slack Notification
    #   uses: act10ns/slack@v1
    #   with: 
    #     status: ${{ job.status }}
    #     steps: ${{ toJson(steps) }}
    #     channel: '#test123'
    #   if: always()
